### ISSUE TITLE
No support for custom User model

### ISSUE THREAD

**Issue by bartTC** [samluescher/django-media-tree#36]
media_tree models and migrations need to use `settings.AUTH_USER_MODEL`, otherwise upon migration you'll get:

```
CommandError: System check identified some issues:

ERRORS:
media_tree.FileNode.created_by: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
media_tree.FileNode.modified_by: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
```
